apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman
  namespace: pacman-app
  annotations: {}
  selfLink: /apis/app.k8s.io/v1beta1/namespaces/pacman-app/applications/pacman
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pacman
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-subscription-0
  namespace: pacman-app
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: deploy
  labels:
    app: pacman
  selfLink: /apis/apps.open-cluster-management.io/v1/namespaces/pacman-app/subscriptions/pacman-subscription-0
spec:
  channel: pacman-app/pacman-app-latest
  placement:
    placementRef:
      name: pacman-placement-0
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-placement-0
  namespace: pacman-app
  labels:
    app: pacman
  selfLink: /apis/apps.open-cluster-management.io/v1/namespaces/pacman-app/placementrules/pacman-placement-0
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/name: pacman

